// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLPredictiveMaintenanceML.Model
{
    public class ModelInput
    {
        [ColumnName("UDI"), LoadColumn(0)]
        public float UDI { get; set; }


        [ColumnName("Product_ID"), LoadColumn(1)]
        public string Product_ID { get; set; }


        [ColumnName("Type"), LoadColumn(2)]
        public string Type { get; set; }


        [ColumnName("Air_temperature_K"), LoadColumn(3)]
        public float Air_temperature_K { get; set; }


        [ColumnName("Process_temperature_K"), LoadColumn(4)]
        public float Process_temperature_K { get; set; }


        [ColumnName("Rotational_speed_rpm"), LoadColumn(5)]
        public float Rotational_speed_rpm { get; set; }


        [ColumnName("Torque_Nm"), LoadColumn(6)]
        public float Torque_Nm { get; set; }


        [ColumnName("Tool_wearmin"), LoadColumn(7)]
        public float Tool_wearmin { get; set; }


        [ColumnName("Machine_failure"), LoadColumn(8)]
        public string Machine_failure { get; set; }


        [ColumnName("TWF"), LoadColumn(9)]
        public float TWF { get; set; }


        [ColumnName("HDF"), LoadColumn(10)]
        public float HDF { get; set; }


        [ColumnName("PWF"), LoadColumn(11)]
        public float PWF { get; set; }


        [ColumnName("OSF"), LoadColumn(12)]
        public float OSF { get; set; }


        [ColumnName("RNF"), LoadColumn(13)]
        public float RNF { get; set; }


    }
}
